# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'cocoapods'
gem 'cocoapods-hmap-prebuilt' ,:path => '../cocoapods-hmap-prebuilt-0.0.7'

# gem "rails"
