# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

use_frameworks! :linkage => :static
#use_modular_headers!

plugin 'cocoapods-hmap-prebuilt'

install! 'cocoapods', generate_multiple_pod_projects: true

target 'MyMainAPP' do

  pod 'SDWebImage','5.12.2'

end
